### ISSUE TITLE
风扇怎么调整转速-电脑会过热

### ISSUE THREAD

**Issue by eeantoss** [sifan077/Mechrevo-code01-Hackintosh#1]

**Comment by sifan077** [comment]
使用这个软件https://github.com/trulyspinach/SMCAMDProcessor/releases修改睿频，我使用过程中其实温度还好

**Comment by eeantoss** [comment]
> 使用这个软件[https://github.com/trulyspinach/SMCAMDProcessor/releases修改睿频，我使用过程中其实温度还好](https://github.com/trulyspinach/SMCAMDProcessor/releases%E4%BF%AE%E6%94%B9%E7%9D%BF%E9%A2%91%EF%BC%8C%E6%88%91%E4%BD%BF%E7%94%A8%E8%BF%87%E7%A8%8B%E4%B8%AD%E5%85%B6%E5%AE%9E%E6%B8%A9%E5%BA%A6%E8%BF%98%E5%A5%BD)
啥时候能硬解第三方浏览器，想用来做开发还是有点困难

**Comment by sifan077** [comment]
我最近忙着考研，没有什么时间研究了，已经很久没关注了，您可以关注这个项目获取最新消息。https://github.com/NootInc/NootedRed

**Comment by eeantoss** [comment]
> 我最近忙着考研，没有什么时间研究了，已经很久没有关注了，您可以关注这个项目获取最新消息。https://github.com/NootInc/NootedRed
好的谢谢
