### ISSUE TITLE
一些发现，求验证

### ISSUE THREAD

**Issue by cnjn** [sifan077/Mechrevo-code01-Hackintosh#2]
amd声卡的新消息:【【AMD·黑苹果】开源项目“AMD专版AppleALC”：给AMD黑果添加AMD ZEN麦克风支持-哔哩哔哩】 https://b23.tv/YEXKAFk

开源链接：https://github.com/qhuyduong/AppleALC
感谢越南老哥逆向，AppleALC在AMD上终于完美。

另，arc浏览器据说可以在amd黑苹果上开启硬解
【可以硬件加速了！ amd 黑苹果chromium硬件加速的浏览器-哔哩哔哩】 https://b23.tv/awcxWVP

睡眠问题据说是要调整SSDT 同考研 暂时没空研究

**Comment by sifan077** [comment]
我现在机器都出了，感觉太折腾了，直接上Nuc8I5BEH了

**Comment by cnjn** [comment]
啊这

**Comment by cnjn** [comment]
啊这
